-- MySQL Script generated by MySQL Workbench
-- Tue Aug 21 16:56:07 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema team-relation-manager
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `team-relation-manager` ;

-- -----------------------------------------------------
-- Schema team-relation-manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `team-relation-manager` DEFAULT CHARACTER SET utf8 ;
USE `team-relation-manager` ;

-- -----------------------------------------------------
-- Table `team-relation-manager`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team-relation-manager`.`team` ;

CREATE TABLE IF NOT EXISTS `team-relation-manager`.`team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team-relation-manager`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team-relation-manager`.`employee` ;

CREATE TABLE IF NOT EXISTS `team-relation-manager`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(128) NOT NULL,
  `first_name` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NULL,
  `team_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_team_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_team`
    FOREIGN KEY (`team_id`)
    REFERENCES `team-relation-manager`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
